global:
  smtp_smarthost: '$ALERT_SMTP_HOST'
  smtp_from: '$ALERT_SMTP_FROM'
  smtp_auth_username: '$ALERT_SMTP_USER'
  smtp_auth_password_file: '/etc/alertmanager/secrets/smtp_pass'
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: '$ADMIN_EMAIL'
    subject: 'Alert: {{ "{{" }} .GroupLabels.alertname {{ "}}" }}'
    send_resolved: true
